language: python
services:
  - docker

before_install:
  - docker build -t mowoe/heartbeat .
  - docker run --name heartbeat -d -p 127.0.0.1:5000:80 -e DB_HOST=$DB_HOST- e DB_PORT=$DB_PORT -e DB_PASSWORD=$DB_PASSWORD -e DB_DATABASE=$DB_DATABASE -e DB_USER=$DB_USER -e DB_TYPE=$DB_TYPE -e OS_BUCKET=$OS_BUCKET -e CELERY_BROKER_URL=$CELERY_BROKER_URL -e OS_TYPE=$OS_TYPE -e AWS_ACCESS_KEY=$AWS_ACCESS_KEY -e AWS_SECRET_KEY=$AWS_SECRET_KEY -e ENDPOINT_URL=$ENDPOINT_URL -e AWS_REGION=$AWS_REGION mowoe/heartbeat
  - docker ps -a

install:
  - sleep 5
  - docker logs heartbeat

script: docker logs heartbeat -f & pip install requests && python tests/endpoint_test.py && bash test.sh

