language: python
services:
  - docker
  - mysql


before_install:
  - mysql -e 'CREATE DATABASE heartbeat;'
  - mysql -e "CREATE USER 'heartbeat'@'%' IDENTIFIED BY 'heartbeat';"
  - mysql -e "GRANT ALL PRIVILEGES ON * . * TO 'heartbeat'@'%';"
  - docker build -t mowoe/heartbeat .
  - docker run --name heartbeat -d -p 127.0.0.1:5000:80 -e DB_HOST=172.17.0.1  -e DB_PORT=3306 -e DB_PASSWORD=heartbeat -e DB_DATABASE=heartbeat -e DB_USER=heartbeat -e DB_TYPE=mysql -e OS_BUCKET=$OS_BUCKET -e CELERY_BROKER_URL=$CELERY_BROKER_URL -e OS_TYPE=$OS_TYPE -e AWS_ACCESS_KEY=$AWS_ACCESS_KEY -e AWS_SECRET_KEY=$AWS_SECRET_KEY -e ENDPOINT_URL=$ENDPOINT_URL -e AWS_REGION=$AWS_REGION mowoe/heartbeat
  - docker ps -a

install:
  - sleep 5
  - docker logs heartbeat

script: docker logs heartbeat -f & pip install requests && python tests/endpoint_test.py && bash test.sh

